[package]
name = "nox"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[dependencies]
rlvm = { git = "https://github.com/antoyo/rlvm" } # "0.0.2"

[lib]
name = "runtime"
crate-type = ["staticlib"]
