[package]
name = "nox"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlvm = { path = "/home/antoni/Ordinateur/OpenSource/rlvm" } # "0.0.2"
