= Nox Language Design

Nox uses pre- and post-conditions checked at compile-time to guarantee
memory and thread safety.

== Thread Safety

----
thread_spawn(value: T)
    ensure is_unique(T)
----

give lifetime to thread (to share references between threads)?

Think about sharing data between threads:
maybe allow the programmer to specify that a value is shareable:

[source,ocaml]
----
let spin_lock(): SpinLock
    assume is_shareable(result)
----

Builtin type constraints (`send`, `sync`) are probably better for that? Does the compiler need to know the concept of shareability?

Safe atomics: https://readthedocs.org/projects/ats-documentation/downloads/pdf/latest/

== Inspirations

 * Try the programming language Whiley.
 * Try to make better than Rust.
 ** Some Rust pitfalls:
 *** https://blog.yossarian.net/2020/05/20/Things-I-hate-about-rust
 *** https://blog.yossarian.net/2022/03/10/Things-I-hate-about-Rust-redux
 * Look at Fortress: https://www.youtube.com/watch?v=EZD3Scuv02g

== Avoiding complexity

 * Instead of type classes, start with implementing the stuff like Hash in the language itself.
 ** I plan to implement this with builtin type constraint like `hash`, `send`, `deref`, `deref_mut`, `ord`, …

== Memory Safety

=== No dangling reference

[source,ocaml]
----
let vector_get(&vector): &a

let vector_push(&vector, a)
    ensure is_unique(&vector)
----

Can we generalize this to allow multiple mutable references on the vector?

Cannot return reference to local variable.
Cannot move non-static reference to move function.

=== No memory leak

For ensuring memory deallocation, have post-condition like:

[source,ocaml]
----
let malloc(): ptr
    ensure result == 0 || will_call(free(result))
----

This seems complicated. Think about something else inspired by linear types, maybe:

[source,ocaml]
----
let malloc(): ptr
    ensure result == 0 || will_consume(result)
----

=== No access to uninitialized values

 * Think about uninitialized values (from malloc).
 * What about partial initialization of structs?
 ** Is this something we want to allow?
 ** Seems like it could be complex for structs containing structs.
 * No implicit free to avoid freeing uninitialized memory.
 * Functions to work with uninitialized memory.

=== Pointer

No ownership for pointers, but ownership for the other types, which would allow creating a struct Unique(pointer)
to have unique pointers?

 * Read https://gankra.github.io/blah/fix-rust-pointers/ to see if anything could be useful.
 * Maybe pointer provenance is useful for optimizations, but I don't really want to support weird architectures.
 ** I believe we might want to forbid usize to pointer casts to help with alias analysis.
 *** Does that require the API added to rust?

=== Inline assembly

For inline assembly, the same system with assumption seems to work:

[source,ocaml]
----
fun test
    assume is_initialized(x) && x > 0
    = (
        let x;
        inline asm …;
        x
    )
----

=== FFI

Pre- and post-conditions can be used on FFI functions in order to use them safely.

=== Heap allocation

 * Allow initializing directly on the heap?
 ** That would probably require C+\\+-like constructor.
 *** The compiler would make sure there are no uninitialized fields at the end of the constructor.
 *** Since we don't want method overloading, would we want named constructor?
 * Since we'll probably have constructor, we could have manually-called destructor for types containing other types (like Vec and Rc).

=== Allocation failure

Open question: what to do to support allocation failure without having something that will infect all the code?

Interesting idea in here:
https://harelang.org/blog/2021-04-28-oom-strategies/

Summary:

 * Depending on whether the pointer type is nullable or not, abort (not nullable pointer) or return NULL (nullable pointer).
 ** Seems dangerous. We probably want to make this explicit.
 * Provide a keyword "static" on functions like append to mention that this will never alloc.

We probably want a different version of the second point, using a pre-condition like:

[source,ocaml]
----
static vec.push(10)
----

will require that the len < capacity in the static case.

Perhaps the static keyword is not even necessary and we can actually use a generic type like:

[source,ocaml]
----
struct NotStatic
struct Static
fun push<T, S = NotStatic>(&self, value: T) ensure S != Static || self.len < self.capacity
vec.push<Static>(10)
----

But this would require the ability to compare types in pre-conditions.

We can probably even put a similar generic type on the Vec itself:

[source,ocaml]
----
struct Vec<T, O = NotStatic>

fun push<T, S = NotStatic>(&self, value: T) ensure S != Static || O != Static || self.len < self.capacity
----

to not have to specify it at every call.

We probably only want to compare some annotated types from libstd in the pre-conditions.

Or perhaps we want to make this a config for the project (that seems like a bad idea, because that would forbid you to use some libraries).

I'm not sure I want to support that level of genericity in the std. Kernel code could just use a different Vec type.

=== Checked dynamic arrays

 * Since we have pre-conditions, we probably can support safe allocas for dynamic arrays.
 * There should probably be an option to tweak the maximum stack size.

Can we also make recursion safe using pre-conditions by checking that the number of recursive calls fit into the stack size?

 * Can we use those dynamic arrays to have IO that read into buffers allocated on the stack?
 * Can we design an API that will allow boxing those buffers without having 2 different functions?
 ** Is this actually useful? Having 2 functions is probably fine.

== Other types of safety

Having integer casts that work without truncation/wrapping, i.e. use pre-conditions to make sure the cast is always safe.

 * The user can write his own predicate that can be used in pre-conditions.
 * Those function require an attribute `#[predicate]`:
 * a predicate is limited in that it cannot call other functions.
 * What to do for integer overflow?
 * TODO: check if something needs to be done regarding variance.

== User-friendliness

=== Less boilerplate

Permissions are an alias for a precondition.

[source,ocaml]
----
perm mut(type) = is_unique(type)

let vec_push(&mut self, element: T) // mut is the permission defined earlier.
----

Maybe we don't need permissions. It could only be types:

[source,ocaml]
----
&mut could be a generic type

type &mut T = *T
ensures is_unique(*T)
----

Probably only libstd should be allowed to use special characters in types.

 * `!` as an operator for `unwrap()` since unwrap is always safe.
 ** Not sure I like that. Maybe just use a refutable binding: `let Some(value) = option`.
 *** What about chaining? If that happens often that we can prove things in such a case, `!` could be useful, for instance: `option!.get(value)!.method`. But I'm not sure this happens much.

Genericity for references to allow `unwrap()` to either return T or &T and methods like `Map.get()` to take T or &T.
Is this something we really want? Doesn't that make the compiler more complex? Is this something used often?

Pony arrow arguments to avoid having to write `get` and `get_mut` methods?
Does this happen enough to justify the complexity it adds?

=== Freeing memory

To free memory at the end of a function:

[source,ocaml]
----
defer free()
----

=== Indexing

 * Allow to use u8, u16, u32 and u64 instead of usize if their size (or value?) <= size_of(usize).
 ** Same for i8, i16, i32, i64 if they are greater than or equal to 0.
 * Check if post-conditions could be used to avoid having an entry API: could Nox know that an indexed value is valid after an insert (even in a HashMap)?

=== Arrays

Allow multiple mutable references to the same array if we can prove that the indexes are different?

Provide type constraints `deref` and `deref_mut` to allow sending a vec to a function taking a slice.

=== Lifetimes

Is the concept of lifetimes implicit or explicit in

[source,ocaml]
----
let vector_get(&vector, &useless): &a
----

?
If it's implicit, it means the compiler needs to do a whole program analysis before being able to infer the lifetimes here.
Isn't it what the type inference do anyway?
Or we can do lifetime elisions like in Rust.

https://haibane-tenshi.github.io/rust-reborrowing/

=== Safe transmute

 * That might be useful to transmute a number/struct to an array of bytes, for instance to change the endianness.
 ** Make sure there's no UB. Look at Rust ideas for this.
 ** Do we actually want this? It looks like it won't be used often.

=== Error handling

Perhaps just use Option and Result and provide some syntax similar to `let-else` in Rust:
https://github.com/rust-lang/rfcs/blob/master/text/3137-let-else.md

 * Do we want to have nullable types instead of Option?

The error in the Result type must implement Copy?

=== How to do zero-cost error handling?

 * Result requires to check for the error even when there are no errors.
 * Is there a way to do something like exceptions where there are no costs when there are no errors?
 * One idea would be to optimize the case when there's no need to unwind (i.e. no variables to free via defer), but I don't like the idea that it doesn't always work.
 * That seems unnecessary because exceptions for error-handling optimization is only useful for recursive algorithms: we can just write it iteratively.

Look at what Zig does.

Maybe something inspired by C's goto:

fun myFunc() =
    if isError() then
        throw SomeError; // goto SomeError

    failure(SomeError): // label SomeError
        handleError()

Take inspiration from this: https://github.com/gamblevore/speedie/blob/main/Documentation/Errors.md

Error traces (https://ziglang.org/documentation/master/#Error-Return-Traces) could be useful, but only in debug mode.

 * Perhaps we can do like Go, e.g. returning tuples (value, err) and having the value uninitialized if there is an error.
 ** That could reduce the boilerplate compared to pattern matching.
 * Maybe `defer_err` would be useful for code only executing when returning an error, for instance to free some memory that doesn't need to be returned when there's an error.
 ** Not sure how common this is, so perhaps it is not useful.

== Strings

 * Use latin1?
 ** No, I believe we can use Unicode and not pay for the unicode validation thanks to pre-conditions.

 * The idea would be that methods requiring a valid unicode string would have a pre-condition is_unicode_valid(self) and
that would require a call to validate_unicode(string) before calling those methods.
 * That might require some form of dependent types here to store whether the string was validated or not.
 ** Perhaps some types could be compile-time types?
 * Think about how to make this more user-friendly. Perhaps with a good API like String::check_from(bytes).

== Module system

 * Anything we can do to avoid deep hierarchy?

== Types

 * Limit tuples to pairs (might be a good idea to avoid having functions returning too much unnamed parameters).
 ** Or even forbid pairs since we don't have closures (that would be a use case for iterator adapters).
 *** Maybe allow them in match expressions?

== Type system

 * Look at what Zig does instead of trait for generics.
 ** It doesn't require any annotation: it just gives a good error message.
 *** This is an interesting idea for functions, but not sure for generic structs.
 ** It actually use compile-time execution to check the time.
 * Having type constraints pre-defined in the language for generics like `eq`, `hash`.
 * Forbid if expressions and other nested expressions as function arguments?
 ** Perhaps have inline expressions (can be used as arguments) and non-inline expression.

== Concurrency

 * Concurrency safety.
 * Can we have sane defaults for non-threaded programs?
 ** I.e. Not requiring global variables to be behind a lock?
 *** That would still require something similar to RefCell.

== Syntax

 * Syntax like `int*l` ptr for lifetimes? Look at lock names syntax in Cyclone.
 * Dereferencing pointers using a suffix operator like `ptr*.field` with possibly another character than `*` to not have
ambiguity with multiplication (not sure it's possible if we allow operator overloading, so maybe `ptr.*.field` like Zig).
 ** Allow the same operator to be overloaded so that you can get a slice from a Vec.
 * Get the address of a variable with `variable@`.
 * Lazy argument to allow function call like `debug_log expensive_call`?
 ** Not sure I like this, but it seems simpler than having macros.
 * That could also be used to avoid having 2 methods: `unwrap_or()` and `unwrap_or_else()`: we could only have `unwrap_or()` that takes a lazy argument.
 * Forbid tabs (for indentations)?
 * match with end to avoid the issue with nested match?
 ** What about the dangling else problem?
 * How to distinguish array indexing and function application with array argument?
 * Non-transitive operator precedence (like in Fortress)? Is is necessary in a strongly-typed language?
 * Owned pointers: `*mut` and `*` (const).
 * Borrowed pointers: `&mut` and `&` (const).
 ** What syntax to use to borrow from an owned pointer?
 *** Is an operator useful for this? Is this useful to know at the call-site whether a pointer ownership is moved or not?

== Standard library

 * writev for atomic printf?
 * Function unreachable where the compiler checks that it is indeed unreachable.
 ** Possibly with the pre-condition `false`?
 ** That would be useful for the `unwrap()` function:
 * Maybe use algorithms from http://0x80.pl/articles/ to implement some algorithms in libstd.

[source,ocaml]
----
fun unwrap(self)
    ensure self.is_some() =
    match self with
    | Some value => value
    | None => unreachable
----

Or do we allow non-exhaustive match when it's proven that the value is only one variant?

=== Iterators

 * I'd like to avoid having iterators, but that seems necessary for types like HashMap.
 * Look at what Go/Hare is doing for this.

== Package manager

Read this article: https://medium.com/@sdboyer/so-you-want-to-write-a-package-manager-4ae9c17d9527

 * See how go modules work.
 * A GitHub repository would contain the index of all the packages.
 * Publishing a new package would send a PR: the CI will check that semver is respected and auto-merge if the CI pass
 and the CI (running on the master branch after the auto-merge) will update the index.
 ** Security:
 *** Auto-merge should only happen if the PR is a package update.
 *** Anything touching files outside of a single package should stop the CI immediately.
 **** Should think of a way to abort the CI when the CI file itself is changed.
 *** Try to think of a better solution as this seems risky, security-wise.

=== Force semantic versioning?

One caveat of this issue is that adding a new dependency can change the version of an existing transitive dependency.
Perhaps we can ask the user if he's OK with the version update (or at least warn him)?

 * I think this idea would work if we add the rule that updating a major version of a dependency requires you to bump
the major version of your library.
 * This also means that adding a new dependency is a major breaking change.
 * Maybe doing like Rust would prevent version numbers to go high quickly: having versions 0.x.y to behave differently
 than >= 1.0.0, i.e. a change of x is a major breaking change.
 * The tool should check:
 ** If there's an auto-trait removed.

=== Allow different versions of the same library?

Forbid having different versions of the same library, using semantic versioning.
I don't like the approach of Haskell either.

==== Zig approach allows users the choose whether they want to allow multiple versions of dependencies or not:

https://github.com/ziglang/zig/issues/943#issuecomment-386458021

==== Elixir approach might be interesting (disallow multiple versions of dependencies):

https://github.com/ziglang/zig/issues/943#issuecomment-878305090

Seems like people had dependency hell in Elixir and I'm not sure how this is different than Haskell.

==== Thoughts from Elm:

https://github.com/elm/compiler/issues/1871#issuecomment-464122832

Seems like they actually allow multiple versions of libraries:
https://elm-lang.org/news/package-manager

==== Maybe allow the user to use different versions by listing the name of the library and the versions used.

=> Seems like the kind of things the users would want to get around by writing another package manager.

Read more about diamond dependency problem.

== Potential issues

 * Self-referencial structs (solution is unmovable types? maybe with a builtin type constraint?).
 ** Do we actually want to fix this issue? It seems only useful for intrusive lists which might not be a pattern that is that useful to support.
 ** Intrusive lists: https://gist.github.com/Darksonn/1567538f56af1a8038ecc3c664a42462
 * Pattern matching smart pointer types.
 ** Seems unnecessarily complex, but it should work for normal heap-allocated values.

== ABI

 * The ABI should be stable.
 * Do we want an ABI compatible with C?
 ** That seems interesting for simplicity (won't have to implement unmangling in many tools like gdb/valgrind/…), but
 might be limiting (what to do for closures?).
 ** Maybe not a good idea: https://faultlore.com/blah/c-isnt-a-language/
 ** An idea to support module would be to forbid underscores in identifiers to have the mangling
 `library_module_function` that is compatible with C.
 ** We could even abuse this system for expressing extern C functions.
 *** Is this a good idea, though?
 ** Look at what Hare does for this.
 ** What about generics?
 *** That's probably not an issue:
 **** The user can manually implement a dynamic version (with enums).
 **** If necessary, the user can also manually export the generic functions in a library distributed as source files
 instead of a binary.
 **** The above can be automated by tools if needed.

== Performance

 * Keep track of compilation speed and binary size compared to C (gcc, clang) and D (because its compiler is fast).
 * Can we optimize based on pre- and post- conditions?
 ** For instance, if we know that a shift value is <= 64, no need to mask it.

== No-go

 * No implicit variant for enum.
 * RAII (but that seems useful for Rc) (the idea is to handle errors for Drop).
 ** Maybe we can give the choice to the user: https://verdagon.dev/blog/raii-next-steps
 ** If we don't have RAII, how would Rc work to drop its inner value?
 *** Perhaps with a builtin type constraint Drop (that wouldn't be a destructor, though, in the sence that it won't
 be automatically called by the compiler; it would only be called by Rc::drop).
 * Traits and OCaml-like modules: I believe those won't be needed thanks to predefined type constraints.
 * Inheritance.
 ** At some point, I thought of using inheritance for allowing to send a Vec to a function taking a slice, but that
    was only as a compiler optimization instead of using Deref. I don't want to add features I don't like for a
    premature optimization.
 * Partial function application.
 * Any type of macros.
 * Tail recursion.
 * Error handling inspired by Common Lisp Condition System.
 ** Former notes pointing in a similar direction:
 *** It seems there's a limited set of actions you would take to handle errors.
 **** Some errors only need to be logged.
 **** Some errors should never happen and should abort.
 **** Others can happen normally, but requires an action (EWOULDBLOCK).
 *** It seems however we cannot decide the action at the definition of the error because this is application-specific.
 **** Should an application error handler be used?
 **** If so, it seems like this wouldn't be sufficient as some errors require local handling instead of global.
 * Panics/exceptions.
